name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packaging
        # Only install PyQt5 for GUI tests in one Python version to save time
        if [ "${{ matrix.python-version }}" == "3.9" ]; then
          pip install PyQt5
        fi
    
    - name: Install test dependencies
      run: |
        pip install coverage
    
    - name: Run tests
      run: |
        if [ "${{ matrix.python-version }}" == "3.9" ]; then
          # Run all tests including GUI tests
          coverage run run_tests.py
        else
          # Skip GUI tests for other Python versions
          python -m unittest discover -p "test_*.py" -k "not TestDockerVersionAnalyzerGUI and not TestOutputRedirector and not TestAnalysisThread"
        fi
    
    - name: Generate coverage report
      if: matrix.python-version == '3.9'
      run: |
        coverage report -m
        coverage xml
    
    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.9'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false